"""Ajustar modelo de productos

Revision ID: 1c00f1c146c7
Revises: cb0c18a27dd1
Create Date: 2025-08-07 18:40:23.487719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c00f1c146c7'
down_revision: Union[str, Sequence[str], None] = 'cb0c18a27dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('stock_minimo', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'stock_minimo')
    # ### end Alembic commands ###
