"""Añadir hashed_password a Usuario

Revision ID: ca4f1b2e6337
Revises: e2639dcdc877
Create Date: 2025-07-15 00:24:43.343436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4f1b2e6337'
down_revision: Union[str, Sequence[str], None] = 'e2639dcdc877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
