"""Añadir color a categorias

Revision ID: cb0c18a27dd1
Revises: 120587c83ea0
Create Date: 2025-08-07 10:50:10.467453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0c18a27dd1'
down_revision: Union[str, Sequence[str], None] = '120587c83ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_descripcion'), 'producto', ['descripcion'], unique=False)
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    op.add_column('categoria', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categoria', 'color')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_index(op.f('ix_producto_descripcion'), table_name='producto')
    op.drop_table('producto')
    # ### end Alembic commands ###
